### PR TITLE
[Translation] [Indonesian]: /Id/advanced/scaling.md

### PR DESCRIPTION
**Pull request by CikiMomogi**
Ready for review.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
CI fails because you changed the bot but it cannot redeploy from your fork. You can fix this by reverting the changes to the notifier. This will make the formatting fail, which you can then fix by merging the upstream branch where this is fixed.

**Comment by KnorpelSenf** [comment]
Ehh okay, I am not sure why that job still tries to run here … maybe just ignore it. Alternatively, you can go to the project settings of this fork and configure that this job is no longer required before merging.

@roj1512 do you think there is anything we can change about the CI config to fix this?

**Comment by CikiMomogi** [comment]
> CI fails because you changed the bot but it cannot redeploy from your fork. You can fix this by reverting the changes to the notifier. This will make the formatting fail, which you can then fix by merging the upstream branch where this is fixed.

Could you do that for me? I do not quite understand where the issue is.

**Comment by fadzikri** [comment]
Did I do something wrong because just agreeing the review without reading the whole of code?

I just a little understand about this advanced code.

**Comment by KnorpelSenf** [comment]
> > CI fails because you changed the bot but it cannot redeploy from your fork. You can fix this by reverting the changes to the notifier. This will make the formatting fail, which you can then fix by merging the upstream branch where this is fixed.
> 
> Could you do that for me? I do not quite understand where the issue is.

@CikiMomogi Yes. I hope it is fixed now.

> Did I do something wrong because just agreeing the review without reading the whole of code?
> 
> I just a little understand about this advanced code.

@fadzikri No, you did everything correctly. The problem was some repo configuration, you do not need to worry about that. It's great if you focus on the content of the documentation and check if everything is understandable and well-written :)

**Comment by roj1512** [comment]
The deploy job runs only if `notifier/` gets modified. Why would you modify `notifier/`?

**Comment by KnorpelSenf** [comment]
> The deploy job runs only if `notifier/` gets modified. Why would you modify `notifier/`?

Because `deno fmt` received an update which caused the formatting of the notifier code to be invalid. Hence, CI would fail.

**Comment by roj1512** [comment]
We can make it run only on the main repository.

**Comment by KnorpelSenf** [comment]
Awesome, I think that would make sense. It does not make much sense for forks to deploy the bot anyway. Could you take care of that? :)

**Pull request merged**
